### ISSUE TITLE
Add build test to check all schemas are valid Avram

### ISSUE THREAD

**Issue by nichtich** [pkiraly/qa-catalogue#409]
Avram Schemas can be checked with `avram -s $file` with avram-js. This issue requires to make all existing schema files valid Avram.

- [x] #405 (not finished yet)
- [x] `src/{main,test}/resources/unimarc/avram-unimarc.json` #408
- [x] cleanup `src/main/resources/marc-schema.json` (this differs from `marc-schema/marc-schema.json` but not sure where it is used at all): #450
- [x] `src/main/resources/marc/authority-schema.avram.json` (requires https://github.com/timathom/marc-schema/pull/12 and possibly more cleanup)
- [ ] remove `src/main/resources/marc/authority-schema.yale.json` and close #373
- [x] cleanup PICA schemas
  - [x] `src/main/resources/pica-schema.json` (should be removed?)
  - [x] remove `src/main/resources/pica/avram-k10plus.json`, use `avram-k10plus-title.json` instead
  - [x] `src/main/resources/pica/avram-k10plus-title.json` (required fix in https://format.k10plus.de/avram.pl)
- [x] `src/test/resources/pica/schema/pica-schema-extra.json` 
- [x] `src/test/resources/pica/schema/pica-schema.json` (should be equal to one of the pica schema files above)

**Comment by nichtich** [comment]
Requires only #450 and #373 to be finished (both seem to be outdated files).
